### ISSUE TITLE
Deprecation of legacy Polymer/paper-* components in 2025.5.1 breaks card navigation tabs in UI editor

### ISSUE THREAD

**Issue by illogicalpartition** [thomasloven/lovelace-layout-card#316]
### My Home Assistant version: 
2025.5.1

### Layout-card version (FROM BROWSER CONSOLE):
2.4.5

### What I am doing:
Editing pre-existing cards and adding new cards to a layout-card using the UI editor.

### What I expected to happen:
- Being able to navigate cards via the numbered tabs.
- Being able to add a new card using the "+" button.

### What happened instead:
- Tabs are just a row of numbers, no longer clickable functional tabs.
- The "+" button does nothing when hovered over or clicked. 

![Image](https://github.com/user-attachments/assets/63466d89-22b7-4a78-ba7c-159e443346de)

### **Minimal** steps to reproduce:
Note: this can be reproduced on both desktop and the mobile app
1. Open a layout-card in UI editor
2. Click "Cards"
3. See broken tabs.

### Error messages from the browser console:
None present.

---

In 2025.5, various legacy Polymer/paper-*  components were retired. The UI editor of layout-card uses "paper-tab" and "paper-tabs" for the card navigation bar; after doing some brief investigation in the dev console, it appear that these have been replaced by "sl-tab" and "sl-tab-group" (I'm assuming there are likely others that were deprecated as well though).

![Image](https://github.com/user-attachments/assets/3b6c8bc9-1208-4de4-ac54-deac0be8dea5)

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Pjarbit** [comment]
I am having the same issue.  The cards tab is no longer visible to me at all.  All of my dashboards are locked as they are unless I want to edit them in yaml.

**Comment by thomasloven** [comment]
Fixed in 2.4.6

**Comment by axel9674** [comment]
I still have the issue, even after updating to version 2.4.6

![Image](https://github.com/user-attachments/assets/324c74f1-e563-4a61-9743-4b38bf14719f)

![Image](https://github.com/user-attachments/assets/bceec8af-7a7e-444d-8ee7-8931c2968a89)

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-config/wiki/Clearing-your-browser-cache

Also, please verify in your browser console that you have the correct version installed. HACS updates can fail sometimes.
